In [ ]:
#Importing basic packages

In [23]:
import pandas as pd
from tensorflow import keras as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score
import joblib

In [ ]:
#Processing the csv

In [4]:
df = pd.read_csv(r"Churn_Modelling.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
df.tail()

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [7]:
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
df['Gender'] = df['Gender'].replace({'Female':0, 'Male':1})
df['Geography'].unique()

C:\Users\agarw\AppData\Local\Temp\ipykernel_14372\1836486842.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender'] = df['Gender'].replace({'Female':0, 'Male':1})


array(['France', 'Spain', 'Germany'], dtype=object)

In [8]:
df['Geography'] = df['Geography'].replace({'France':0, 'Spain': 1, 'Germany': 2})

C:\Users\agarw\AppData\Local\Temp\ipykernel_14372\1445365493.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Geography'] = df['Geography'].replace({'France':0, 'Spain': 1, 'Germany': 2})


In [9]:
df

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619          0       0   42       2       0.00              1   
1             608          1       0   41       1   83807.86              1   
2             502          0       0   42       8  159660.80              3   
3             699          0       0   39       1       0.00              2   
4             850          1       0   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771          0       1   39       5       0.00              2   
9996          516          0       1   35      10   57369.61              1   
9997          709          0       0   36       7       0.00              1   
9998          772          2       1   42       3   75075.31              2   
9999          792          0       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [ ]:
#Splitting input and output data and further splitting training and testing data

In [10]:
X = df.iloc[:,0:-1].values
Y = df.iloc[:,-1].values

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
X_train

array([[8.3700000e+02, 1.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 5.0972600e+04],
       [6.0100000e+02, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 7.7977690e+04],
       [5.2100000e+02, 2.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 2.0491150e+04],
       ...,
       [6.9700000e+02, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 6.4771610e+04],
       [7.2700000e+02, 2.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 1.8096232e+05],
       [7.3500000e+02, 2.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1495722e+05]])

In [12]:
X_train
X_test
len(X_train)
len(X_test)

2000

In [ ]:
#Transforming the data to fit between -1 to 1 in order to normalize the input

In [13]:
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [15]:
Y_train

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
#Model creation and training

In [16]:
ann= tf.models.Sequential()
ann.add(tf.layers.Dense(units=8, activation="relu"))
ann.add(tf.layers.Dense(units=8, activation="relu"))
ann.add(tf.layers.Dense(units=8, activation="relu"))
ann.add(tf.layers.Dense(units=1, activation="sigmoid"))
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])
print("Model created")

Model created


In [17]:
ann.fit(X_train, Y_train, batch_size=15, epochs=100)

Epoch 1/100
534/534 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.7889 - loss: 0.5550
Epoch 2/100
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8032 - loss: 0.4453
Epoch 3/100
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8227 - loss: 0.4206
Epoch 4/100
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8213 - loss: 0.4206
Epoch 5/100
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8316 - loss: 0.4099
Epoch 6/100
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8342 - loss: 0.4048
Epoch 7/100
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8283 - loss: 0.4112
Epoch 8/100
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8275 - loss: 0.4082
Epoch 9/100
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8353 - loss: 0.4053
Epoch 10/100
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8340 - loss: 0.3933
Epoch 11/100
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8403 - loss: 0.3890
Epoch 12/100
534/534 ━━━━━━━━━━━━━━━━━━━━

In [ ]:
#Predicting the output for test data

In [18]:
Y_pred=ann.predict(X_test)
Y_pred=(Y_pred>0.5).astype(int)
Y_pred

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


array([[0],
       [1],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [21]:
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test,Y_pred)

[[1563   58]
 [ 215  164]]


0.8635

In [ ]:
#Dumping the Aritifical Neural Network trained model and Scaler used to normalise the data input using joblib

In [25]:
model_filename = "churn_prediction_model.pkl"
joblib.dump(ann, model_filename)
print(f"Model has been dumped to {model_filename}")

Model has been dumped to churn_prediction_model.pkl


In [26]:
scaler_filename = "scaler.pkl"
joblib.dump(sc, scaler_filename)
print(f"Scaler has been dumped to {scaler_filename}")

Scaler has been dumped to scaler.pkl
